# Generated by Django 3.0.9 on 2020-08-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('title', models.TextField()),
                ('author', models.TextField()),
                ('click', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
