# Generated by Django 3.0.8 on 2020-08-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='make_college_vote',
            fields=[
                ('college_no', models.AutoField(primary_key=True, serialize=False)),
                ('college_title', models.CharField(max_length=45)),
                ('college_content', models.TextField(max_length=2000)),
                ('college_deadline', models.DateTimeField()),
                ('college_c1_name', models.CharField(max_length=45)),
                ('college_c2_name', models.CharField(max_length=45)),
                ('college_c3_name', models.CharField(max_length=45)),
                ('college_c4_name', models.CharField(max_length=45)),
                ('college_c5_name', models.CharField(max_length=45)),
                ('college_c1_ex', models.TextField(max_length=2000)),
                ('college_c2_ex', models.TextField(max_length=2000)),
                ('college_c3_ex', models.TextField(max_length=2000)),
                ('college_c4_ex', models.TextField(max_length=2000)),
                ('college_c5_ex', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='make_dept_vote',
            fields=[
                ('dept_no', models.AutoField(primary_key=True, serialize=False)),
                ('dept_title', models.CharField(max_length=45)),
                ('dept_content', models.TextField(max_length=2000)),
                ('dept_deadline', models.DateTimeField()),
                ('dept_c1_name', models.CharField(max_length=45)),
                ('dept_c2_name', models.CharField(max_length=45)),
                ('dept_c3_name', models.CharField(max_length=45)),
                ('dept_c4_name', models.CharField(max_length=45)),
                ('dept_c5_name', models.CharField(max_length=45)),
                ('dept_c1_ex', models.TextField(max_length=2000)),
                ('dept_c2_ex', models.TextField(max_length=2000)),
                ('dept_c3_ex', models.TextField(max_length=2000)),
                ('dept_c4_ex', models.TextField(max_length=2000)),
                ('dept_c5_ex', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='make_school_vote',
            fields=[
                ('school_no', models.AutoField(primary_key=True, serialize=False)),
                ('school_title', models.CharField(max_length=45)),
                ('school_content', models.TextField(max_length=2000)),
                ('school_deadline', models.DateTimeField()),
                ('school_c1_name', models.CharField(max_length=45)),
                ('school_c2_name', models.CharField(max_length=45)),
                ('school_c3_name', models.CharField(max_length=45)),
                ('school_c4_name', models.CharField(max_length=45)),
                ('school_c5_name', models.CharField(max_length=45)),
                ('school_c1_ex', models.TextField(max_length=2000)),
                ('school_c2_ex', models.TextField(max_length=2000)),
                ('school_c3_ex', models.TextField(max_length=2000)),
                ('school_c4_ex', models.TextField(max_length=2000)),
                ('school_c5_ex', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('noitce_pk', models.AutoField(primary_key=True, serialize=False)),
                ('notice_title', models.CharField(max_length=45)),
                ('notice_updateday', models.DateTimeField(verbose_name='date published')),
                ('notice_writer', models.CharField(max_length=45)),
                ('notice_count', models.IntegerField()),
                ('notice_content', models.TextField(max_length=2000)),
            ],
        ),
    ]
