# Generated by Django 3.0.8 on 2020-08-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestVote',
            fields=[
                ('sgvote_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('sgvote_title', models.CharField(max_length=45)),
                ('sgvote_writer', models.CharField(max_length=45)),
                ('sgvote_count', models.IntegerField(blank=True, null=True)),
                ('sgvote_updateday', models.DateField()),
            ],
            options={
                'db_table': 'suggest_vote',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UndergraduateVote',
            fields=[
                ('ud_vt_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('ud_vt_name', models.CharField(max_length=45)),
                ('ud_vt_dday', models.DateField()),
                ('ud_category1', models.CharField(blank=True, max_length=45, null=True)),
                ('ud_category2', models.CharField(blank=True, max_length=45, null=True)),
                ('ud_category3', models.CharField(blank=True, max_length=45, null=True)),
                ('ud_category4', models.CharField(blank=True, max_length=45, null=True)),
                ('ud_category5', models.CharField(blank=True, max_length=45, null=True)),
                ('ud_vt_result1', models.CharField(blank=True, max_length=45, null=True)),
                ('ud_vt_result2', models.CharField(blank=True, max_length=45, null=True)),
                ('ud_vt_result3', models.CharField(blank=True, max_length=45, null=True)),
                ('ud_vt_result4', models.CharField(blank=True, max_length=45, null=True)),
                ('ud_vt_result5', models.CharField(blank=True, max_length=45, null=True)),
                ('ud_final_result', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'undergraduate_vote',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VoteList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'vote_list',
                'managed': False,
            },
        ),
    ]
