# Generated by Django 3.0.8 on 2020-09-28 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0004_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_comple'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='Complete',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='MajorVote',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Notice',
        ),
        migrations.DeleteModel(
            name='SchoolVote',
        ),
        migrations.DeleteModel(
            name='SuggestOther',
        ),
        migrations.DeleteModel(
            name='SuggestVote',
        ),
        migrations.DeleteModel(
            name='UndergraduateVote',
        ),
        migrations.DeleteModel(
            name='VoteList',
        ),
    ]
